version: '3'
services:
        web1:
            image: nginx
            container_name: con-1
            volumes:
                - depo:/tmp
                - ./web1:/usr/share/nginx/html
            ports:
                - 8080:80
            networks:
                - bridge_network
        web2:
            build: .
            container_name: con-2
            ports:
                - 9080:80
            networks:
                - bridge_network


networks:
      bridge_network:
            driver: bridge
volumes:
    depo:
        
        