version: '3'

services:
  web1:
      image: nginx
      depends_on:
            - db
      ports:
            - 8080:80
      volumes: 
            - ./depo1:/usr/share/nginx/html
      container_name: servis1
  web2:
      image: nginx
      depends_on: 
            - db
      ports:
            - 6060:80
      volumes:
            - ./depo2:/usr/share/nginx/html
      container_name: servis2
  db:
      image: mysql:5.7
      restart: always
      ports: 
          - 3306:3306
      environment:
          - MYSQL_ROOT_PASSWORD=1234
          - MYSQL_USER=erkan
          - MYSQL_DATABASE=demodb
          - MYSQL_PASSWORD=1234
      container_name: datalar


