version: '3'
services:
    db:
          image: mysql:5.7
          container_name: data
          restart: always
          volumes: 
                  - db_data:/var/lib/mysql
          environment:
              MYSQL_DATABASE: wordpress
              MYSQL_USER: erkan
              MYSQL_PASSWORD: 1234
              MYSQL_ROOT_PASSWORD: 12345
          networks:
                  - bridge_network
    wordpress:
          depends_on: 
                  - db
          image: wordpress
          restart: always
          volumes:
                  - /var/www/html
          ports:
                  - "8080:80"
          environment:
              WORDPRESS_DB_HOST: db:3306
              WORDPRESS_DB_USER: erkan
              WORDPRESS_DB_PASSWORD: 1234
          networks:
                  - bridge_network
    phpmy:
          depends_on: 
                  - db
          image: phpmyadmin/phpmyadmin
          restart: always
          ports:
                  - "7080:80"
          networks:
                  - bridge_network
          environment:
              PMA_HOST: db
              MYSQL_ROOT_PASSWORD: 12345
    drupal:
          depends_on: 
                  - db
          image: drupal
          restart: always
          ports:
                  - 9080:80
          environment:
              MYSQL_DATABASE: drupal
              MYSQL_USER: erkan
              MYSQL_PASSWORD: 1234
          volumes:
                  - /var/www/html/sites
                  - /var/www/html/profiles
                  - /var/www/html/themes
                  - /var/www/html/modules
                  - /var/www/private
          networks:
                  - bridge_network




              

volumes: 
    db_data:
networks: 
    bridge_network:

              
              

